name:                spinner
version:             0.1.0.0
github:              "mpdairy/haskell-xpilot-ai/spinner"
license:             LicenseRef-AllRightsReserved
author:              "Matt Parker"
maintainer:          "mpdairy@gmail.com"
copyright:           ""

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the readme

dependencies:
  - base
  - containers
  - envy
  - xpilot-ai
  - mtl
  - newtype
  - pretty-simple
  - protolude
  - stm
  - template-haskell
  - text
  - transformers
  - unordered-containers

default-extensions:
  - BangPatterns
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - OverloadedStrings
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections


library:
  ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -j
  - -O2
  extra-libraries: cAI
  source-dirs:
    - src
  
include-dirs:
  - "src"

executables:
  spinner:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -O2
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - spinner
    - containers
    - xpilot-ai
    - text
